version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python3 /app/cybernexvpn/cybernexvpn_bot/bot/main.py

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: celery -A cybernexvpn_bot.core.celery.app worker --loglevel=info
    depends_on:
      - redis
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: uvicorn api.main:app --host 0.0.0.0 --port ${FAST_API_PORT}
    depends_on:
      - redis
    ports:
      - "${FAST_API_PORT}:${FAST_API_PORT}"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - redis_data:/data

volumes:
  redis_data:
