version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./cybernexvpn/.env
    command: python3 /app/cybernexvpn/cybernexvpn_bot/bot/main.py

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    restart: always
    depends_on:
      - redis
    command: celery -A cybernexvpn.cybernexvpn_bot.core.celery.app worker --loglevel=info --pool=solo

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8888:8888"
    depends_on:
      - redis
    command: uvicorn api.main:app --host 0.0.0.0 --port 8888

  redis:
    image: "redis:alpine"
    ports:
      - "6379"
    restart: on-failure
    volumes:
      - redis_data:/data

volumes:
  redis_data:
