version: '3'
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${SOURCE_WG_CONFIGS_PATH}:${WG_CONFIGS_PATH}
    env_file:
      - ./.env

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: celery -A celery_config.celery_app worker --loglevel=info
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: celery -A celery_config.celery_app beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
