version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${SOURCE_WG_CONFIGS_PATH}:${WG_CONFIGS_PATH}
      - ${SOURCE_SYNC_CONFIG_FILE_PATH}:${SYNC_CONFIG_FILE_PATH}
    env_file:
      - .env
    network_mode: "host"
    privileged: true
    command: python3 /app/vpnBot/bot/main.py
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ${SOURCE_WG_CONFIGS_PATH}:${WG_CONFIGS_PATH}
      - ${SOURCE_SYNC_CONFIG_FILE_PATH}:${SYNC_CONFIG_FILE_PATH}
    command: celery -A celery_config.celery_app worker --loglevel=info
    depends_on:
      - redis
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ${SOURCE_WG_CONFIGS_PATH}:${WG_CONFIGS_PATH}
      - ${SOURCE_SYNC_CONFIG_FILE_PATH}:${SYNC_CONFIG_FILE_PATH}
    command: celery -A celery_config.celery_app beat --loglevel=info
    depends_on:
      - redis

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: uvicorn server.main:app --host 0.0.0.0 --port ${FAST_API_PORT}
    depends_on:
      - redis
    ports:
      - "${FAST_API_PORT}:${FAST_API_PORT}"

  redis:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"