from aiogram.fsm.state import State

PROMO_CODE_EXPECTING_STATE = State("PROMO_CODE_EXPECTING_STATE")
# ADDING_DEVICE_STATE = State("ADDING_DEVICE_STATE")
EDIT_DEVICE_NAME_EXPECTING_STATE = State("EDIT_DEVICE_NAME_EXPECTING_STATE")
